### ISSUE TITLE
Allow stdout redirect for further processing

### ISSUE THREAD

**Issue by tallpsmith** [rcoh/angle-grinder#29] opened 2018-07-31 11:50 UTC
The default live update is amazing, but I tried to pipe stdout of a query to do some further processing with `awk`, as I was hoping to get a cumulative sum (which would be a nice aggregator to have like SumoLogic has).

On OSX at least, attempting to redirect stdout seems to hang the process, and nothing comes out.

**Comment by rcoh** [comment] 2018-07-31 15:12
Hmm that should definitely work. Can you send your query or anything else
to help reproduce?

**Comment by rcoh** [comment] 2018-07-31 15:14
Actually I might know -- I think it's waiting for the input to end since it
can't write an aggregate multiple times. Ctrl+c should actually cause it to
emit an aggregate to a file

**Comment by tallpsmith** [comment] 2018-08-01 04:10
I was running:

```
cat loggers.txt| agrind '* | parse "*" as logger | count by logger' > foo
```

where `loggers.txt` just contained a simple string.  

I first ran the bash command without the `> foo` to time it.  It took 80 seconds and output as expected.

I then ran it with the redirect, waited more than 2 minutes and then CTRL-C'd the process.  but `foo` is empty still.

```
$ agrind --version
ag 0.7.2
```
(brew installed).

Example file:

```
$ head loggers.txt
[OrbStatisticsControl
[it.timing.LoggerSink
[essFaxDeliveryAction
[it.timing.LoggerSink
[it.timing.LoggerSink
[main.TasksRepository
[it.timing.LoggerSink
[it.timing.LoggerSink
[it.timing.LoggerSink
[it.timing.LoggerSink
```

**Comment by tallpsmith** [comment] 2018-08-01 04:25
ah yes, using `head` (to make the file input smaller) works fine:

```
psmith@paul ~/temp/au1 $ head loggers.txt| agrind '* | parse "*" as logger | count by logger' > foo
psmith@paul ~/temp/au1 $ cat foo
logger                       _count
-------------------------------------------
[it.timing.LoggerSink        7
[main.TasksRepository        1
[OrbStatisticsControl        1
[essFaxDeliveryAction        1
```

So input/output buffering issue?

I'd be happy to try to build from source and try out the tip of branches (good chance to get my shirt sleeves rolled up with the Rust ecosystem)

**Comment by rcoh** [comment] 2018-08-01 04:32
Yeah go for it! It should be straightforward given a working rust install.
Sounds like a performance bug if it's much slower going to stdout. I'll
take a look

**Comment by tallpsmith** [comment] 2018-08-01 05:31
Running 0.7.4 via git checkout and `cargo install`. Same behaviour.

interesting observations:

* OSX shows agrind buring about 1 core, so it's definitely doing something
* Spindump (attached) shows the threads doing merge-sort so that does also indicate it's "doing something"

So your idea on performance difference based on the standard output does sound about right, but I am not sure why that would be so.  Will be interesting to see what you find!

[agrind-Spindump.txt](https://github.com/rcoh/angle-grinder/files/2248115/agrind-Spindump.txt)

**Comment by tallpsmith** [comment] 2018-08-01 05:32
Also for context, the size of this file is 757MB:

```
$ wc  loggers.txt
 36071659 36073508 793576498 loggers.txt
```

**Comment by rcoh** [comment] 2018-08-01 20:27
Hey Paul,
  I just pushed 0.7.5 which should fix the performance bug. We never print
in tty mode, which meant the tracker of the last time we printed never got
updated. The rest of the code was structured to see that our last print was
stale and to recompute the aggregates on every row. The fix will defer all
aggregate printing until the very end when we're in tty mode so it should
be much faster. Let me know if that fixes it for you when building from
source -- if it does, I'll push this version to brew.

**Comment by rcoh** [comment] 2018-08-01 20:31
Should be fixed by 7eae04

**Comment by rcoh** [comment] 2018-08-01 20:33
By the way @tallpsmith not sure what kind of cumulative you mean, but you can do things like:

`* | parse "*" as logger | count by logger | sum` not sure if that's what you meant

**Comment by tallpsmith** [comment] 2018-08-01 22:36
taking the tip of master (which still says `0.7.4` btw, even though there's a `0.7.5` tag)

```
psmith@paul ~/temp/au1 $ time cat loggers.txt| agrind '* | parse "*" as logger | count by logger' > foo

real	1m15.623s
user	2m15.256s
sys	0m10.300s```

Great Success!  https://media.giphy.com/media/a0h7sAqON67nO/giphy.gif

(and it's even faster than with it displaying to tty..)

**Comment by tallpsmith** [comment] 2018-08-01 22:40
Also in response to:

> `* | parse "*" as logger | count by logger | sum not sure if that's what you meant`



```
 cat loggers.txt| agrind '* | parse "*" as logger | count by logger | sum'
Failure parsing query. Parse failed at: Error(Code(CompleteStr("| sum"), Eof))
```

I'm not sure how the heck Sumologic does it, but I was thinking of something like the `accum` operator: https://help.sumologic.com/Search/Search-Query-Language/Search-Operators/accum

So a running total along side the previous column.  That was the idea I was getting towards anyway.

**Comment by tallpsmith** [comment] 2018-08-01 22:40
thanks for the quick turn around!

**Closed** 2018-08-01 22:45 UTC
